
#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := basic

COMPONENT_ADD_INCLUDEDIRS := main/conf/SSD1306-frab

include $(IDF_PATH)/make/project.mk