
#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := basic

# frab needs this
EXTRA_CPPFLAGS := -DESP8266

include $(IDF_PATH)/make/project.mk